[book]
title = "예제로 배우는 러스트 (Rust by Example) 한국어판"
description = "A description"
author = "The Rust Community"

[output.html.playpen]
editable = true
editor = "ace"

[output.html.fold]
enable = true
